### ISSUE TITLE
国服是不是用不了呀

### ISSUE THREAD

**Issue by zh1011** [BlossomiShymae/Needlework.Net#3]
![image](https://github.com/user-attachments/assets/88d0001c-4151-4842-94ad-421d29aac067)

**Comment by BlossomiShymae** [comment]
- What is your exact OS?
- Have you tried running the program as administrator?
- Can you try running the attached program and show the error output if any?
[BlossomiShymae.GrrrLCU.Demo.exe.zip](https://github.com/user-attachments/files/16636542/BlossomiShymae.GrrrLCU.Demo.exe.zip)

**Comment by zh1011** [comment]
> * 您具体的操作系统是什么？
> * 您是否尝试以管理员身份运行该程序？
> * 您能否尝试运行附加的程序并显示错误输出（如果有）？
>   [BlossomiShymae.GrrrLCU.Demo.exe.zip](https://github.com/user-attachments/files/16636542/BlossomiShymae.GrrrLCU.Demo.exe.zip)
> 
> 发生此错误的原因是底层库`BlossomiShymae.GrrrLCU`无法[检索进程命令行](https://github.com/BlossomiShymae/GrrrLCU/blob/main/BlossomiShymae.GrrrLCU/ProcessInfo.cs#L24C13-L46C14)。现在我已更新它，如果您运行附加的程序，我可以更好地了解您的错误。

Thank you for your product. I am a window platform and I can test it tomorrow

**Comment by zh1011** [comment]
> * 您具体的操作系统是什么？
> * 您是否尝试以管理员身份运行该程序？
> * 您能否尝试运行附加的程序并显示错误输出（如果有）？
>   [BlossomiShymae.GrrrLCU.Demo.exe.zip](https://github.com/user-attachments/files/16636542/BlossomiShymae.GrrrLCU.Demo.exe.zip)
> 
> 发生此错误的原因是底层库`BlossomiShymae.GrrrLCU`无法[检索进程命令行](https://github.com/BlossomiShymae/GrrrLCU/blob/main/BlossomiShymae.GrrrLCU/ProcessInfo.cs#L24C13-L46C14)。现在我已更新它，如果您运行附加的程序，我可以更好地了解您的错误。

我是中国服的lol 用的是腾讯的wegame,中国服的lol能用您的程序吗？

**Comment by BlossomiShymae** [comment]
It hasn't been tested with Wegame, so probably not. x3

**Comment by zh1011** [comment]
> 它尚未在 WeGame 上测试过，所以可能不行。x3

![image](https://github.com/user-attachments/assets/ee3b6e6e-b1eb-40e5-b5a6-74e0fcb39137)
Chinese lol has many users

**Comment by BlossomiShymae** [comment]
Upon further research, it seems to be an access control issue from attempting to read the League Client process. I will attempt to find a solution or workaround soon.

**Comment by zh1011** [comment]
> Upon further research, it seems to be an access control issue from attempting to read the League Client process. I will attempt to find a solution or workaround soon.

thank so mush

**Comment by ytx222** [comment]
Hello, I also encountered the same error
```
Unhandled exception. System.InvalidOperationException: Failed to open process for reading
   at BlossomiShymae.GrrrLCU.ProcessInfo..ctor(Process process)
   at BlossomiShymae.GrrrLCU.Connector.GetProcessInfo()
   at BlossomiShymae.GrrrLCU.Connector.SendAsync(HttpMethod httpMethod, String path, HttpContent httpContent, CancellationToken cancellationToken)
   at BlossomiShymae.GrrrLCU.Connector.GetAsync(String path, CancellationToken cancellationToken)
   at BlossomiShymae.GrrrLCU.Connector.GetFromJsonAsync[T](String path, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Controller.GetSummonerAsync()
   at Controller.StartAsync()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```
Is there any progress please

**Comment by BlossomiShymae** [comment]
If anyone wants to help solve this issue, here is the relevant code for the underlying library. As I don't have access to WeGame, I unfortunately am in a bit of a pickle. :x

https://github.com/BlossomiShymae/GrrrLCU/blob/main/BlossomiShymae.GrrrLCU/ProcessFinder.cs#L20-L34
https://github.com/BlossomiShymae/GrrrLCU/blob/main/BlossomiShymae.GrrrLCU/ProcessInfo.cs#L23-L45

**Comment by ytx222** [comment]
Oh, okay, unfortunately I am a front-end and not very familiar with this aspect.
By the way, is this API obtained by querying the client? If the client in each region is different, the API is not completely consistent. Or is it exactly the same?

**Comment by BlossomiShymae** [comment]
In regions like North America or Europe, the LCU API is accessed by querying the client process for the port token and password. The underlying LCU API should be the same across all regions, but the client process can differ as shown here.

**Comment by ytx222** [comment]
There may be some inconsistencies recently...
Because we have added cross-region matching, there may be cases where the name is the same, which adds an extra id to each person, such as name#123456, which caused errors when I searched by name, but I can't find the latest documentation...

**Comment by ytx222** [comment]
In addition, the method of directly querying process parameters should not work on our side. Anyway, my final implementation method is to query the Windows registry to obtain the installation directory, and then query the latest log file, and extract the address and key from the log file. This is very strange, isn’t it?

Thanks for your reply
